config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Root Settings for authenticated and unauthenticated users
  devise_scope :user do
    authenticated :user do
      root to: 'dashboard#index', as: :authenticated_root
    end

    unauthenticated do
      root to: 'devise/sessions#new'
    end
  end

  # Devise routes for users
  devise_for :users, skip: [:registrations]

  as :user do
    get 'users/edit/:id' => 'devise/registrations#edit', as: 'edit_user_registration'
    put 'users/:id' => 'devise/registrations#update'
  end

  # Standard routes
  resources :users, only: [:show]
  resources :batches
  resources :observations
  resources :devices, only: [:index]

  # Static page controllers
  get '/dashboard', to: 'dashboard#index'
  get '/journal', to: 'journal#index'
  get '/calendar', to: 'calendar#index'

  # Task-related routes
  resources :todos do
    member do
      post :done
      post :undone
    end
  end

  resources :notifications do
    collection do
      delete :clear_all
    end
  end

  resources :samples, only: [:index] do
    collection do
      get :general
      get :rooms
      get :harvest
    end
  end


  # Nested resources for grows
  resources :grows, except: %i[edit update new create] do
    resources :harvests, only: [:show]
    resources :weeks
    resources :observations
    resources :subjects do
      resources :observations
    end

    member do
      get :print_qr
    end
  end

  # Room-related resources
  resources :rooms, only: [:show] do
    resources :devices, only: [:show] do
      post :query, on: :member
      resources :events # Hinzufügen von Events unter Devices
    end

    resources :events
  end

  # Default events route (falls eigenständige events benötigt werden)
  resources :events
  resources :harvests, only: %i[index new]

  # Admin namespace
  namespace :admin do
    get '/dashboard/gpio', to: 'dashboard#gpio'

    resources :users, except: [:show] do
      member do
        get :update_password
      end
    end

    resources :grows, only: %i[edit update new create destroy] do
      resources :harvests, except: %i[index show] do
        resources :batches, except: %i[index show]
      end
      resources :subjects do
        post :move_to, on: :member
      end
    end

    resources :rooms do
      resources :devices, only: %i[index edit update new create destroy] do
        post :start, on: :member
        post :stop, on: :member
        resources :events
      end
    end

    resources :strains
    resources :data_types
    resources :batches
    resources :harvests
    resources :weeks

    resources :conditions do
      collection do
        get 'update', to: 'conditions#update'
      end
    end
    resources :batches, only: [:index, :show, :new, :create, :update, :destroy]

    resources :scenarios do
      member do
        get :load_condition_type_form
      end
      member do
        post 'run'
        get :export
        post :import
        get :import
      end
    end

    resources :devices do
      post :start, on: :member
      post :stop, on: :member
      post :query, on: :member
    end

    resources :circuits
    resources :components
    resources :device_scripts

    resources :scenarios do
      member do
        get :load_condition_type_form
      end
      member do
        post 'run'
      end
      collection do
        get :export
        post :import
      end
    end

    resources :condition_groups
    resources :conditions
    resources :operations

    resources :alerts do
      member do
        post :test
        post :trigger
      end
    end
    resources :categories
    resources :resources
    resources :observation_resources
    resources :issues, only: [:new, :destroy]

    resource :settings

    get '/', to: 'users#index'
  end

  # API namespace
  namespace :api do
    namespace :v1 do
      get '/context', to: 'context#index'

      resources :users, only: [:show] do
        resources :push_devices, only: [:create]
      end

      resources :devices, only: %i[index show update] do
        post :start, on: :member
        post :stop, on: :member
        resources :events # API-Unterstützung für verschachtelte Events unter Devices
      end

      resources :rooms
      resources :grows do
        resources :subjects
      end
      resources :subjects do
        resources :observations
      end
      resources :scenarios
      resources :conditions
      resources :operations
      resources :observations
      resources :events

      resources :data_types, only: %i[index show] do
        resources :samples, defaults: { format: :json }, only: %i[index show]
      end

      resources :samples, defaults: { format: :json }, only: %i[index show create]
    end
  end

  # API documentation
  apipie

  # Test route
  get 'test/index'
end

app/models/grow.rb
# frozen_string_literal: true

# Grow
class Grow < ApplicationRecord
  include BirthTypeEnum

  attr_accessor :strain_id

  default_scope { order(start_date: :desc) }

  enum grow_status: {
    scheduled: 0,
    seedling: 1,
    vegging: 2,
    flowering: 3,
    flushing: 4,
    drying: 5,
    curing: 6,
    done: 7,
    aborted: 8
  }

  enum substrate: { soil: 0, coco: 1, hydro: 2, aero: 3 }

  enum flowering: { photoperiodic: 0, autoflowering: 1 }

  has_many :subjects, dependent: :delete_all
  has_many :weeks, dependent: :delete_all
  has_many :observations, dependent: :delete_all
  has_many :events, as: :eventable, dependent: :destroy
  has_one :harvest

  validates :birth_type, presence: true
  validates :description, presence: true
  validates :grow_status, presence: true
  validate :validate_number_of_subjects
  validate :validate_birth_type_and_mother

  def validate_number_of_subjects
    return unless birth_type == 'from_clone'
    return unless number_of_subjects.blank?

    errors.add(:number_of_subjects, "can't be blank when birth type is 'from clone'.")
  end

  def validate_birth_type_and_mother
    return unless birth_type == 'from_clone'

    errors.add(:mother_id, "must be selected when birth type is 'from clone'.")
  end

  def name
    "##{id} - #{description}"
  end

  def harvestable?
    drying? or curing? or done?
  end

  def active_subjects
    subjects.joins(:grow).where.not('grows.grow_status': %i[done aborted])
  end

  def nb_weeks
    (end_date - start_date).to_i / 7
  end

  def status_badge_class
    case grow_status
    when 'done'
      'badge-light border'
    when 'aborted'
      'badge-danger'
    when 'seedling', 'vegging', 'flowering'
      'badge-success'
    when 'flushing'
      'badge-info'
    when 'drying', 'curing'
      'badge-warning'
    else
      'badge-primary'
    end
  end

  def generate_weeks
    weeks.destroy_all

    return if start_date.nil?

    current_date = start_date
    end_date = current_date + 7.days
    week_index = 0

    %i[seedling vegging flowering flushing drying curing].each do |type|
      send(:"#{type}_weeks").times do
        generate_weeks_with_type(type, week_index, current_date, end_date)
        current_date += 7.days
        end_date = current_date + 7.days
        week_index += 1
      end
    end
  end

  def generate_weeks_with_type(type, index, start_date, end_date)
    Week.create(grow_id: id, week_type: type, week_number: index + 1, start_date:, end_date:)
  end

  def current_week
    now = Date.today
    # puts "#{start_date} < #{now} < #{end_date}"
    # return true if now >= start_date && now <= end_date
    weeks.where('? >= start_date AND ? <= end_date', now, now).first
  end

  def bg_color_for_week(week_index)
    days = week_index * 7
    week_start_date = start_date + days.days
    week_end_date = week_start_date + 7.days
    now = Date.today

    if now > week_end_date
      return 'success'

    elsif (week_start_date < now) && (now < week_end_date)
      return 'primary'
    end

    'secondary'
  end

  def progress_color
    now = Date.today

    return 'success' if done?
    return 'danger' if end_date.present? && now > end_date

    'primary'
  end

  # rubocop:disable Lint/UnreachableCode
  def progress_percents
    # FIXME
    return
    start_time = start_date.to_time
    end_time = end_date.to_time

    return 100 if done?
    return 0 if !start_time || !end_time || (end_time == start_time)
    return 0 if Time.now < start_time

    r = (((Time.now - start_time) / (end_time - start_time)) * 100.0).round
    return 100 if r > 100

    r
  end
  # rubocop:enable Lint/UnreachableCode

  def self.active_grows
    Grow.where.not('grows.grow_status': %i[done aborted])
  end

  def self.inactive_grows
    Grow.where('grows.grow_status': %i[done aborted])
  end

  def self.update_status
    Grow.where.not(grow_status: %i[done aborted]).find_each do |grow|
      next unless grow.auto_update_status?

      old_status = grow.grow_status
      next if old_statusold_status == grow.grow_status = grow.current_week&.week_type&.to_sym
      next if old_status == grow.grow_status

      Event.create!(
        event_type: :cron,
        eventable: grow,
        message: "Grow <b>#{grow.description}</b> status updated to <b>#{grow.grow_status}</b>"
      )
      grow.save!
    end
  end
end

app/controllers/admin/grows_controller.rb
# frozen_string_literal: true

module Admin
  # Admin::GrowsController
  class GrowsController < Admin::AdminController
    before_action :set_grow, only: %i[edit update destroy]

    # GET /grows/new
    def new
      @grow = Grow.new(birth_type: 'from_seed')

      add_breadcrumb 'Grows', grows_path
      add_breadcrumb 'New'
    end

    # GET /grows/1/edit
    def edit
      add_breadcrumb 'Edit'
    end

    # POST /grows
    # POST /grows.json
    # rubocop:disable Metrics/MethodLength
    def create
      @grow = Grow.new(grow_params)

      respond_to do |format|
        if @grow.save
          # create subjects
          if @grow.birth_type == 'from_clone'
            @grow.number_of_subjects.times do |i|
              room = Room.find(params[:room])
              next unless room

              Subject.create!(
                name: "Subject #{i + 1}",
                grow_id: @grow.id,
                room_id: room.id,
                birth_type: @grow.birth_type,
                strain_id: params[:strain_id],
                mother_id: @grow.mother_id
              )
            end
          end
          @grow.generate_weeks

          format.turbo_stream
          format.html { redirect_to @grow, notice: 'Grow was successfully created.' }
          format.json { render :show, status: :created, location: @grow }
        else
          format.turbo_stream
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @grow.errors, status: :unprocessable_entity }
        end
      end
    end
    # rubocop:enable Metrics/MethodLength

    # PATCH/PUT /grows/1
    # PATCH/PUT /grows/1.json
    def update
      respond_to do |format|
        if @grow.update(grow_params)
          @grow.generate_weeks

          format.html { redirect_to @grow, notice: 'Grow was successfully updated.' }
          format.json { render :show, status: :ok, location: @grow }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @grow.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /grows/1
    # DELETE /grows/1.json
    def destroy
      @grow.destroy
      respond_to do |format|
        format.html { redirect_to grows_url, notice: 'Grow was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_grow
      @grow = Grow.find(params[:id])

      add_breadcrumb "Grow ##{@grow.id}"
    end

    # rubocop:disable Metrics/MethodLength
    def grow_params
      params.require(:grow).permit(
        :grow_status,
        :auto_update_status,
        :birth_type,
        :mother_id,
        :strain_id,
        :description,
        :start_date,
        :seedling_weeks,
        :vegging_weeks,
        :flowering_weeks,
        :flushing_weeks,
        :drying_weeks,
        :curing_weeks,
        :substrate,
        :flowering,
        :estimated_weight_by_square_meter,
        :number_of_subjects
      )
    end
    # rubocop:enable Metrics/MethodLength
  end
end

app/controllers/api/v1/grows_controller.rb
# frozen_string_literal: true

module Api
  module V1
    # GrowsController for the API
    class GrowsController < ApiController
      before_action :set_grow, only: [:show]

      # GET /grows
      api :GET, '/v1/grows', 'Get a list of grows'
      param :limit, :number, desc: 'Limit number of grows (default: 100, max: 1000)'
      param :offset, :number, desc: 'Offset of grows'
      param :sort_direction, %w[asc desc], desc: 'The sort direction key'
      param :sort_column, %w[id created_at updated_at], desc: 'The sort column name'

      def index
        @grows = Grow.all

        @grows = if params.key?(:sort_direction) && params.key?(:sort_column)
                   @grows.order("#{params[:sort_column]} #{params[:sort_direction]}")
                 else
                   @grows.order(created_at: :asc)
                 end

        @grows = if params.key? :limit
                   @grows.limit(params[:limit])
                 else
                   @grows.limit(100)
                 end

        return unless params.key? :offset

        @grows = @grows.offset(params[:offset])

        # TODO: rewrite using builder to optimize load and avoid includes
        # render json: @grows,
        #   include: [
        #  :observations,
        #     :subjects => {:methods => [:strain_name]},
        #     :weeks => {:methods => [:color]}
        #   ],
        #   methods: [
        #     :progress_percents,
        #     :end_date
        #   ]
      end

      # GET /grows/1
      api :GET, '/v1/grows/:id', 'Get a grow item'
      def show
        render json: @grow, include: %i[subjects weeks observations], methods: %i[progress_percents end_date]
      end

      private

      def set_grow
        @grow = Grow.find(params[:id])
      end
    end
  end
end

app/controllers/grows_controller.rb
# frozen_string_literal: true

# GrowsController
class GrowsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_grow, only: %i[show print_qr]

  # GET /grows
  # GET /grows.json
  def index
    @grows = Grow.all

    #add_breadcrumb 'Grows'
  end

  # GET /grows/1
  # GET /grows/1.json
  def show
    @todos_json = current_user.todos.to_json(methods: %i[text url color start_date end_date])
    @weeks_json = @grow.weeks.joins(:grow).where.not('grows.grow_status': %i[done
                                                                             aborted]).to_json(methods: %i[text url
                                                                                                           color])
    @observations_json = @grow.observations.all.to_json(methods: %i[start_date end_date text url])
    @issues_json = Issue.where(issue_status: :open).to_json(methods: %i[start_date end_date text url color])

    respond_to do |format|
      format.html
      format.json { render json: @grow.to_json(include: :subjects) }
    end
  end

  def print_qr; end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_grow
    @grow = Grow.find(params[:id])

    #add_breadcrumb "Grow ##{@grow.id}"
  end

  def grow_params
    params.require(:grow).permit(
      :grow_status,
      :description,
      :start_date,
      :seedling_weeks,
      :vegging_weeks,
      :flowering_weeks,
      :flushing_weeks,
      :drying_weeks,
      :curing_weeks,
      :substrate,
      :flowering,
      :number_of_subjects
    )
  end
end

app/helpers/grows_helper.rb
# frozen_string_literal: true

# GrowsHelper
module GrowsHelper
end

app/views/grows/_form.html.erb
<%= form_with(model: grow, local: true, data: { turbo: false }, class: "col-md-12 col-lg-8 mx-auto") do |form| %>
  <h1>
    <%= grow.new_record? ? "New Grow" : "Editing Grow" %>
    <div class="float-end">
      <% unless grow.new_record? %>
        <%= form_with(url: [:admin, grows], method: :post, class: "d-inline") do %>
          <%= submit_tag 'Destroy', class: "btn btn-sm btn-outline-danger" %>
        <% end %>
      <% end %>
      <%= form.submit "Save", class: "btn btn-primary" %>
    </div>
  </h1>

  <hr>

  <% if grow.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(grow.errors.count, "error") %> prohibited this grow from being saved:</h2>

      <ul>
      <% grow.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :description, class: 'form-label' %>
    <%= form.text_field :description, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :grow_status, class: 'form-label' %>
    <%= form.select :grow_status, options_for_select(Grow.grow_statuses.keys.to_a.map{ |t| [t(t), t] }, form.object.grow_status), {}, class: "form-control" %>
  </div>

  <hr>

  <div class="mb-3">
    <div class="row">
      <div class="col-md-4">
        <%= form.label :substrate, class: 'form-label' %>
        <%= form.select :substrate, options_for_select(Grow.substrates.keys.to_a.map{ |t| [t(t), t] }, form.object.substrate), {}, class: "form-control" %>
      </div>
      <div class="col-md-4">
        <%= form.label :flowering, class: 'form-label' %>
        <%= form.select :flowering, options_for_select(Grow.flowerings.keys.to_a.map{ |t| [t(t), t] }, form.object.flowering), {}, class: "form-control" %>
      </div>
    </div>
  </div>

  <hr>

  <div class="mb-3">
    <div class="row">
      <div class="col-md-4">
        <%= form.label "Create subjects", class: 'form-label' %>
        <%= form.number_field :number_of_subjects, class: "form-control", disabled: !grow.new_record? %>
      </div>

      <div class="col-md-4">
        <%= form.label "Put them in room", class: 'form-label' %>
        <%= select_tag :room, options_from_collection_for_select(Room.all, "id", "name"), class: "form-control", disabled: !grow.new_record? %>
      </div>
    </div>
  </div>

  <br>
  <hr>

  <div class="mb-3">
    <div class="row">
      <div class="col-md-6">
        <%= form.label "Start Date", class: 'form-label' %>
        <%= form.hidden_field :start_date, value: fdate(form.object.start_date), class: "form-control weekpicker", id: "weekpicker-#{form.object.id}-start_date", data: { toggle: "datetimepicker", target: "#weekpicker-#{form.object.id}-start_date" } %>
      </div>
      <div class="col-md-6">
        <div class="mb-3">
          <%= form.label :seedling_weeks, class: 'form-label' %>
          <%= form.number_field :seedling_weeks, value: form.object.seedling_weeks, min: 0, max: 52, class: "form-control" %>
        </div>

        <div class="mb-3">
          <%= form.label :vegging_weeks, class: 'form-label' %>
          <%= form.number_field :vegging_weeks, value: form.object.vegging_weeks, min: 0, max: 52, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= form.label :flowering_weeks, class: 'form-label' %>
          <%= form.number_field :flowering_weeks, value: form.object.flowering_weeks, min: 0, max: 52, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= form.label :flushing_weeks, class: 'form-label' %>
          <%= form.number_field :flushing_weeks, value: form.object.flushing_weeks, min: 0, max: 52, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= form.label :drying_weeks, class: 'form-label' %>
          <%= form.number_field :drying_weeks, value: form.object.drying_weeks, min: 0, max: 52, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= form.label :curing_weeks, class: 'form-label' %>
          <%= form.number_field :curing_weeks, value: form.object.curing_weeks, min: 0, max: 52, class: "form-control" %>
        </div>

      </div>
    </div>
  </div>
<% end %>

app/views/grows/_grow.html.erb
<div class="col-12 mb-3">
	<div class="card">
	  <h5 class="card-header">
			<%= link_to user_path(grow) do %>
  			<i class="bi-flower1 h4"></i>
				<%= grow.description %>
			<% end %>
	  	<div class="float-end d-none d-md-block">
	  		<span class="badge <%= grow.status_badge_class %> ms-2"><%= grow.grow_status %></span>
		    <span class="badge bg-info"><%= grow.substrate %></span>
		    <span class="badge bg-secondary"><%= grow.flowering %></span>
	  	</div>
	  </h5>
	  <div class="card-body">
	  	From <b><%= fdate(grow.start_date) %></b> to <b><%= fdate(grow.end_date) %></b>
	    <div class="progress my-2">
	      <div class="progress-bar bg-<%= grow.progress_color %>" role="progressbar" style="width: <%= grow.progress_percents %>%" aria-valuenow="<%= grow.progress_percents %>" aria-valuemin="0" aria-valuemax="100"><%= grow.progress_percents %>%</div>
	    </div>

	    <h5 class="d-inline-flex"><span class="badge bg-success"><%= grow.subjects.count %> subjects</span></h5>

	    <% if grow.current_week %>
	    	<h5 class="d-inline-flex"><span class="badge bg-primary">W<%= grow.current_week.week_number %></span></h5>
	    <% end %>

	    <div class="float-end">
	    	<%= link_to new_grow_observation_path(grow), class: "btn btn-sm btn-outline-primary d-flex align-items-center" do %>
		      <i class="bi-plus h4"></i> <i class="bi-chat-right-dots h4"></i>
		    <% end %>
	    </div>
	  </div>
	</div>
</div>

app/views/grows/_grows.html.erb
<table class="table">
  <thead>
    <tr>
      <th width="340px">Name</th>
      <th>Progress</th>
      <th>End date</th>
      <th>Status</th>
      <th>Substrate</th>
      <th>Flowering</th>
      <th>Subjects</th>
      <th width="160px"></th>
    </tr>
  </thead>

  <tbody>
    <% grows.each do |grow| %>
      <tr>
        <td class="text-primary"><b><%= link_to "#{grow.name}", grow %></b></td>
        <td>
          <div class="progress">
            <div class="progress-bar bg-<%= grow.progress_color %>" role="progressbar" style="width: <%= grow.progress_percents %>%" aria-valuenow="<%= grow.progress_percents %>" aria-valuemin="0" aria-valuemax="100"><%= grow.progress_percents %>%</div>
          </div>
        </td>
        <td class="text-<%= grow.progress_color %>"><small><%= fdate grow.end_date %></small></td>
        <td><span class="badge bg-<%= grow.status_badge_class %>"><%= grow.grow_status %></span></td>
        <td><span class="badge bg-info"><%= grow.substrate %></span></td>
        <td><span class="badge bg-secondary"><%= grow.flowering %></span></td>
        <td><%= grow.subjects.count %></td>
        <td>
          <%= link_to "View", grow, class: "btn btn-sm btn-outline-secondary" %>
          <%= link_to "Edit", edit_admin_grow_path(grow), class: "btn btn-sm btn-outline-success" %>
          <%= link_to "New", new_grow_observation_path(grow), class: "btn btn-sm btn-outline-primary" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/grows/_weeks.html.erb
<div id="grows-weeks" class="dhx_cal_container" style='width:100%; height:800px;'
  data-todos-json='<%= @grow.weeks.to_json.html_safe %>'
  data-weeks-json='<%= @weeks_json.html_safe %>'
  data-observations-json='<%= @observations_json.html_safe %>'>
  <div class="dhx_cal_navline">
  <div class="dhx_cal_prev_button">&nbsp;</div>
  <div class="dhx_cal_next_button">&nbsp;</div>
  <div class="dhx_cal_today_button"></div>
  <div class="dhx_cal_date"></div>
  <div class="dhx_cal_tab" name="day_tab" style="right:204px;"></div>
  <div class="dhx_cal_tab" name="week_tab" style="right:140px;"></div>
  <div class="dhx_cal_tab" name="month_tab" style="right:76px;"></div>
</div>
<div class="dhx_cal_header"></div>
<div class="dhx_cal_data"></div>

<%= javascript_tag do %>import './views/admin/grows/weeks';;<% end %>

app/views/grows/edit.html.erb
<%= render 'form', grow: @grow %>

app/views/grows/index.html.erb
<h1>
  Grows
  <div class="float-end">
    <%= link_to new_admin_grow_path, class: "btn btn-primary d-flex align-items-center" do %>
      <i class="bi-plus my-1 h5"></i> Grow
    <% end %>
  </div>
</h1>

<h4>Running Grows</h4>
<%= render partial: "grows/grows", locals: {grows: @grows.where.not(grow_status: [:aborted, :done]) } %>

<h4>Terminated Grows</h4>
<%= render partial: "grows/grows", locals: {grows: @grows.where(grow_status: [:aborted, :done]) } %>

app/views/grows/new.html.erb
<%= render 'form', grow: @grow %>

app/views/grows/print_qr.html.erb
<h1>
	Subjects QR
	<div class="float-end">
		<%= link_to 'Back', [:admin, @grow], class: "btn btn-light border" %>
		<%= link_to '#', onclick: 'window.print();return false;', class: "btn btn-outline-primary" do %>
			<i class="bi-print h4"></i> Print
		<% end %>
	</div>
</h1>

<hr>

<div class="row">
	<% @grow.subjects.each do |subject| %>
		<div class="col-4">
			<%= image_tag subject.generate_qr(5), class: "qr-code d-block mx-auto" %>
			<p class="text-center">
				<%= link_to subject.name, [:admin, subject.grow, subject] %>
			</p>
		</div>
	<% end %>
</div>

app/views/grows/show.html.erb
<h1>
  <%= @grow.name %>

 <div class="float-end d-inline-flex">
    <%= link_to 'Back', grows_path, class: "btn btn-light border d-flex align-items-center me-2" %>

    <% if @grow.harvestable?  %>
      <% if @grow.harvest.nil? %>
        <%= link_to new_admin_grow_harvest_path(@grow), class: "btn btn-success d-flex align-items-center me-2" do %>
          <i class="bi-flower1 my-1 h5"></i>
          Harvest
        <% end %>
      <% else %>
        <%= link_to [@grow, @grow.harvest], class: "btn btn-success d-flex align-items-center me-2" do %>
          <i class="bi-flower1 my-1 h5"></i>
          Harvest
        <% end %>
      <% end %>
    <% end %>

    <%= link_to 'Edit', edit_admin_grow_path(@grow), class: "btn btn-success d-flex align-items-center me-2" %>
    <%= link_to new_admin_grow_subject_path(@grow), class: "btn btn-info d-flex align-items-center me-2" do %>
      <i class="bi-plus my-1 h5"></i>Subject
    <% end %>
    <%= link_to new_grow_observation_path(@grow), class: "btn btn-outline-primary d-flex align-items-center" do %>
      <i class="bi-plus my-1 h5"></i>Observation<i class="bi-comment-dots h4"></i>
    <% end %>
</div>

<hr>

<div>
  <div class="float-end ms-3 h6">
    <span class="badge bg-primary"><%= @grow.grow_status %></span>
    <span class="badge bg-info"><%= @grow.substrate %></span>
    <span class="badge bg-secondary"><%= @grow.flowering %></span>
  </div>

  <div style="padding-top: 5px;">
    <div class="text-muted">
      <small>From <b><%= fdate @grow.start_date %></b> to <b><%= fdate @grow.end_date %></b></small>
    </div>
    <div class="progress">
      <div class="progress-bar bg-<%= @grow.progress_color %>" role="progressbar" style="width: <%= @grow.progress_percents %>%" aria-valuenow="<%= @grow.progress_percents %>" aria-valuemin="0" aria-valuemax="100"><%= @grow.progress_percents %>%</div>
    </div>
  </div>
</div>

<hr>

<h4>
  Weeks
  <div class="float-end">
    <div class="col-sm-4 col-md-3 col-lg-2 mb-3">
      <%= link_to icon("bi-plus h4") + ' Week', new_grow_week_path(@grow), class: "btn btn-sm btn-outline-secondary" %>
    </div>
  </div>
</h4>

<%= render partial: "calendar/calendar", locals: {
  todos_json: @todos_json,
  weeks_json: @weeks_json,
  observations_json: @observations_json,
  issues_json: @issues_json } %>

<br>

<h4>
  Subjects
  <div class="float-end">
    <%= link_to print_qr_grow_path(@grow), class: "text-muted", style: "font-size: 11px;" do %>
      <i class="bi-print h4"></i> Print QR
    <% end %> -
  </div>
</h4>

<div class="row">
  <%= render partial: "admin/subjects/subjects", locals: { subjects: @grow.subjects } %>
</div>

<h4>Observations</h4>

<div class="row">
  <div class="col-sm-12 col-md-12 col-lg-8">
    <%= render partial: "observations/observations", locals: { observations: @grow.observations } %>
  </div>
</div>