config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Root Settings for authenticated and unauthenticated users
  devise_scope :user do
    authenticated :user do
      root to: 'dashboard#index', as: :authenticated_root
    end

    unauthenticated do
      root to: 'devise/sessions#new'
    end
  end

  # Devise routes for users
  devise_for :users, skip: [:registrations]

  as :user do
    get 'users/edit/:id' => 'devise/registrations#edit', as: 'edit_user_registration'
    put 'users/:id' => 'devise/registrations#update'
  end

  # Standard routes
  resources :users, only: [:show]
  resources :batches
  resources :observations
  resources :devices, only: [:index]

  # Static page controllers
  get '/dashboard', to: 'dashboard#index'
  get '/journal', to: 'journal#index'
  get '/calendar', to: 'calendar#index'

  # Task-related routes
  resources :todos do
    member do
      post :done
      post :undone
    end
  end

  resources :notifications do
    collection do
      delete :clear_all
    end
  end

  resources :samples, only: [:index] do
    collection do
      get :general
      get :rooms
      get :harvest
    end
  end


  # Nested resources for grows
  resources :grows, except: %i[edit update new create] do
    resources :harvests, only: [:show]
    resources :weeks
    resources :observations
    resources :subjects do
      resources :observations
    end

    member do
      get :print_qr
    end
  end

  # Room-related resources
  resources :rooms, only: [:show] do
    resources :devices, only: [:show] do
      post :query, on: :member
      resources :events # Hinzufügen von Events unter Devices
    end

    resources :events
  end

  # Default events route (falls eigenständige events benötigt werden)
  resources :events
  resources :harvests, only: %i[index new]

  # Admin namespace
  namespace :admin do
    get '/dashboard/gpio', to: 'dashboard#gpio'

    resources :users, except: [:show] do
      member do
        get :update_password
      end
    end

    resources :grows, only: %i[edit update new create destroy] do
      resources :harvests, except: %i[index show] do
        resources :batches, except: %i[index show]
      end
      resources :subjects do
        post :move_to, on: :member
      end
    end

    resources :rooms do
      resources :devices, only: %i[index edit update new create destroy] do
        post :start, on: :member
        post :stop, on: :member
        resources :events
      end
    end

    resources :strains
    resources :data_types
    resources :batches
    resources :harvests
    resources :weeks

    resources :conditions do
      collection do
        get 'update', to: 'conditions#update'
      end
    end
    resources :batches, only: [:index, :show, :new, :create, :update, :destroy]

    resources :scenarios do
      member do
        get :load_condition_type_form
      end
      member do
        post 'run'
        get :export
        post :import
        get :import
      end
    end

    resources :devices do
      post :start, on: :member
      post :stop, on: :member
      post :query, on: :member
    end

    resources :circuits
    resources :components
    resources :device_scripts

    resources :scenarios do
      member do
        get :load_condition_type_form
      end
      member do
        post 'run'
      end
      collection do
        get :export
        post :import
      end
    end

    resources :condition_groups
    resources :conditions
    resources :operations

    resources :alerts do
      member do
        post :test
        post :trigger
      end
    end
    resources :categories
    resources :resources
    resources :observation_resources
    resources :issues, only: [:new, :destroy]

    resource :settings

    get '/', to: 'users#index'
  end

  # API namespace
  namespace :api do
    namespace :v1 do
      get '/context', to: 'context#index'

      resources :users, only: [:show] do
        resources :push_devices, only: [:create]
      end

      resources :devices, only: %i[index show update] do
        post :start, on: :member
        post :stop, on: :member
        resources :events # API-Unterstützung für verschachtelte Events unter Devices
      end

      resources :rooms
      resources :grows do
        resources :subjects
      end
      resources :subjects do
        resources :observations
      end
      resources :scenarios
      resources :conditions
      resources :operations
      resources :observations
      resources :events

      resources :data_types, only: %i[index show] do
        resources :samples, defaults: { format: :json }, only: %i[index show]
      end

      resources :samples, defaults: { format: :json }, only: %i[index show create]
    end
  end

  # API documentation
  apipie

  # Test route
  get 'test/index'
end

app/models/room.rb
# frozen_string_literal: true

# Room
class Room < ApplicationRecord
  attr_accessor :scenario_id

  has_many :subjects
  has_many :devices, dependent: :destroy
  has_many :events, as: :eventable, dependent: :destroy

  has_many :observations, through: :subjects

  has_many :samples, through: :devices

  has_many :room_scenarios, dependent: :destroy
  has_many :scenarios, through: :room_scenarios

  validates :name, presence: true

  enum room_type: { box: 0, closet: 1, room: 2, greenhouse: 3 }

  has_many_attached :camshots

  def all_events
    Event.where(eventable_type: 'Device', eventable_id: devices)
         .or(Event.where(eventable_type: 'Room', eventable_id: id))
  end

  def active_subjects
    subjects.joins(:grow).where.not('grows.grow_status': %i[done aborted])
  end

  def last_sample(data_type)
    samples.where(data_type:).order(created_at: :desc).limit(1).first
  end

  def current_temperature
    data_type = DataType.where(name: 'temperature').first

    sample = last_sample(data_type)

    return nil if sample.nil?

    "#{sample.value} #{sample.unit}"
  end

  def current_humidity
    data_type = DataType.where(name: 'humidity').first

    sample = last_sample(data_type)

    return nil if sample.nil?

    "#{sample.value} #{sample.unit}"
  end

  def total_watts
    w = 0

    devices.each do |device|
      #w += device.watts if device.watts && device.watts > 0.0
    end

    w.round(2)
  end

  # rubocop:disable Metrics/CyclomaticComplexity
  def kwh_day
    total_kwh = 0

    scenarios.each do |scenario|
      next unless scenario.enabled?

      scenario.condition_groups.each do |condition_group|
        condition_group.operations.each do |operation|
          next unless operation.command == 'start'

          # running_time = calculate_running_time(condition_group)
          running_time = 24

          next unless running_time.positive?

          device = devices.find_by(device_type: operation.device_type)
          #total_kwh += running_time * device.watts / 1000 if device
        end
      end
    end

    total_kwh.round(2)
  end
  # rubocop:enable Metrics/CyclomaticComplexity

  def kwh_month
    kd = kwh_day
    return (kd * 30).round(2) if kd.positive?

    0
  end

  private

  def calculate_running_time(condition_group)
    running_time = 24

    condition_group.conditions.where(condition_type: :date).each do |condition|
      running_time = (condition.end_time - condition.start_time).abs / 3600
    end

    running_time
  end

  # def take_camshot
  # 	# Get the first camera device
  # 	camera_device = devices.where(device_type: :camera).first
  # 	return unless camera_device

  # 	# Generate temporary image path
  # 	tmp_name = "camshot-image-#{Time.now.to_i}"
  # 	tmp_image_path = "/tmp/#{tmp_name}.jpeg"

  # 	begin
  # 		# Capture image based on the type of camera device
  # 		case camera_device.product_reference
  # 		when "usb_webcam"
  # 			# Capture image from USB webcam with fswebcam
  # 			system("/usr/bin/fswebcam -d /dev/video0 --flip v --no-banner -r 384x288 #{tmp_image_path}")
  # 		when "rpi_camera_module_v2"
  # 			# No implementation as per original code
  # 		when "ustreamer"
  # 			# Capture image from ustreamer
  # 			system("curl http://magicbox.read-write.fr:8888/snapshot -o #{tmp_image_path}")
  # 		else
  # 			return # Exit method if no known camera type is matched
  # 		end

  # 		# Attach the image to the camshots collection
  # 		if File.exist?(tmp_image_path)
  # 			self.camshots.attach(io: File.open(tmp_image_path), filename: "image-#{Time.now.strftime('%s%L')}.jpeg")
  # 			# Delete the temporary file
  # 			File.delete(tmp_image_path)
  # 		else
  # 			puts "Failed to create image file: #{tmp_image_path}"
  # 		end
  # 	rescue => e
  # 		Rails.logger.error "Error taking camshot: #{e.message}"
  # 	ensure
  # 		# Ensure the temporary file is deleted even if errors occur
  # 		File.delete(tmp_image_path) if File.exist?(tmp_image_path)
  # 	end
  # end

  def dark?
    require 'rmagick'
    active_storage_disk_service = ActiveStorage::Service::DiskService.new(root: "#{Rails.root}/storage/")
    path = active_storage_disk_service.send(:path_for, camshots.last.blob.key)

    img = Magick::Image.read(path).first
    puts img.channel_mean

    return true if (img.channel_mean[0] <= 7000) && (img.channel_mean[1] <= 1000)

    false
  end
end

app/controllers/admin/rooms_controller.rb
# frozen_string_literal: true

module Admin
  # Admin::RoomsController
  class RoomsController < Admin::AdminController
    before_action :authenticate_user!
    before_action :set_room, only: %i[show edit update destroy]

    # GET /rooms
    # GET /rooms.json
    def index
      @rooms = Room.all
    end

    # GET /rooms/new
    def new
      @room = Room.new
    end

    # POST /rooms
    # POST /rooms.json
    def create
      @room = Room.new(room_params)
      respond_to do |format|
        if @room.save
          # if room_params[:scenario_id]
          #   scenario = Scenario.find(room_params[:scenario_id])
          #   @room.scenario = scenario if scenario
          # else
          #   @room.scenario = nil
          # end

          format.html { redirect_to @room, notice: 'Room was successfully created.' }
          format.json { render :show, status: :created, location: @room }
        else
          format.html { render :new }
          format.json { render json: @room.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /rooms/1
    # PATCH/PUT /rooms/1.json
    def update
      respond_to do |format|
        if @room.update(room_params)
          # if room_params[:scenario_id].present?
          #   scenario = Scenario.find(room_params[:scenario_id])
          #   @room.scenario = scenario if scenario
          # else
          #   @room.scenario = nil
          # end

          format.html { redirect_to @room, notice: 'Room was successfully updated.' }
          format.json { render :show, status: :ok, location: @room }
        else
          format.html { render :edit }
          format.json { render json: @room.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /rooms/1
    # DELETE /rooms/1.json
    def destroy
      @room.destroy
      respond_to do |format|
        format.html { redirect_to admin_rooms_url, notice: 'Room was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    def room_params
      params.require(:room).permit(:name, :room_type, :length, :width, :height, scenario_ids: [])
    end
  end
end

app/controllers/api/v1/rooms_controller.rb
# frozen_string_literal: true

module Api
  module V1
    # RoomsController for the API
    class RoomsController < ApiController
      before_action :set_room, only: [:show]

      # GET /rooms
      api :GET, '/v1/rooms', 'Get a list of rooms'
      param :limit, :number, desc: 'Limit number of rooms (default: 100, max: 1000)'
      param :offset, :number, desc: 'Offset of rooms'
      param :sort_direction, %w[asc desc], desc: 'The sort direction key'
      param :sort_column, %w[id created_at updated_at], desc: 'The sort column name'

      def index
        @rooms = Room.all

        @rooms = if params.key?(:sort_direction) && params.key?(:sort_column)
                   @rooms.order("#{params[:sort_column]} #{params[:sort_direction]}")
                 else
                   @rooms.order(created_at: :asc)
                 end

        @rooms = if params.key? :limit
                   @rooms.limit(params[:limit])
                 else
                   @rooms.limit(100)
                 end

        return unless params.key? :offset

        @rooms = @rooms.offset(params[:offset])
      end

      # GET /grows/1
      api :GET, '/v1/rooms/:id', 'Get a room item'
      def show
        render json: @room, include: %i[subjects devices events observations scenario]
      end

      private

      def set_room
        @room = Room.find(params[:id])
      end
    end
  end
end

app/controllers/rooms_controller.rb
# frozen_string_literal: true

# RoomsController
class RoomsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_room, only: [:show]

  # GET /rooms/1
  # GET /rooms/1.json
  def show
    #add_breadcrumb @room.name, @room

    @camera = @room.devices.where(device_type: :camera).first
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_room
    @room = Room.find(params[:id])
  end

  def room_params
    params.require(:room).permit(:name, :room_type, :length, :width, :height, :scenario_id)
  end
end

app/helpers/rooms_helper.rb
# frozen_string_literal: true

# RoomsHelper
module RoomsHelper
end

app/views/rooms/_camshot.html.erb
<!--  <% if room.camshots.count > 0 %>
  <div class="card mb-3">
    <%= image_tag room.camshots.last, class: "card-img-top" %>
    <div class="card-body">
      <%= link_to take_camshot_room_path(room), method: :post, class: "btn btn-primary" do %>
        <%= icon "fas", "camera" %>
      <% end %>
      <div class="float-right">
        <span class="text-muted">The room is <%= room.dark? ? "dark" : "lit" %></span>
      </div>
    </div>
  </div>
<% else %>
  <% if room.observations.last and room.observations.last.pictures.first %>
  <div class="card mb-3">
    <%= image_tag room.observations.last.pictures.first, class: "card-img-top" %>
  </div>

  <small class="text-muted"><i><%= fdatetime room.observations.last.pictures.first.created_at %></i></small>

  <% end %>
<% end %> -->

app/views/rooms/_room_devices.html.erb
<div class="row">
  <% devices = room.devices.where.not(device_state: :idle) %>
  <div class="col-sm-12 col-md-6 col-lg-6">
    <% if devices.empty? %>
      <div class="card mb-4">
        <div class="card-body p-4">
          <p class="p-4 text-center">
            <i>No device registered yet</i>
            <br>
            <%= link_to new_admin_room_device_path(room), class: "btn btn-outline-info mt-4 d-flex align-items-center" do %>
              <i class="bi-plus my-1 h5"></i> Device
            <% end %>
          </p>
        </div>
      </div>
    <% else %>
      <% devices.each do |device| %>
        <div class="card mb-3">
          <div class="card-body">
            <h5 class="card-title">
              <span class="badge bg-<%= device.state_color %>"><%= device.device_state.titleize %></span>
              &nbsp;
              <%= link_to device.name, [device.room, device], style: "text-decoration: none; color: #666" %>
              <div class="float-end">
                <div class="dropdown">
                  <button class="btn btn-sm dropdown-toggle bg-transparent text-muted" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="bi-pci-card h4 me-4"></i>
                  </button>
                  <div class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenuButton">
                    <%= link_to start_admin_room_device_path(device.room, device), method: :post, class: "dropdown-item text-success" do %>
                      <i class="bi-play h4"></i> Start
                    <% end %>
                    <%= link_to stop_admin_room_device_path(device.room, device), method: :post, class: "dropdown-item text-danger" do %>
                      <i class="b-stop h4"></i> Stop
                    <% end %>

                    <div class="dropdown-divider"></div>
                    <%= link_to edit_admin_room_device_path(device.room, device), class: "dropdown-item" do %>
                      <i class="bi-pencil h4"></i> Edit
                    <% end %>
                  </div>
                </div>
              </div>
            </h5>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="col-sm-12 col-md-6 col-lg-6">
    <% sensor_devices = room.devices.where(device_state: :idle) %>
    <% if sensor_devices.empty? %>
      <div class="card mb-4">
        <div class="card-body p-4">
          <p class="p-4 text-center">
            <i>No sensor data yet</i>
            <br>
            <%= link_to new_admin_room_device_path(room), class: "btn btn-outline-info mt-4 d-flex align-items-center" do %>
              <i class="bi-plush my-1 h5"></i> Device
            <% end %>
          </p>
        </div>
      </div>
    <% else %>
      <% sensor_devices.each do |device| %>
        <% device.data_types.each do |data_type| %>
          <div class="card mb-4">
            <div class="card-body">
              <h5 class="card-title">
                <%= link_to data_type.name.capitalize, [device.room, device] %>
                <div class="float-end">
                  <div class="dropdown">
                    <button class="btn btn-sm dropdown-toggle bg-transparent text-muted" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <i class="bi-pci-card h4 me-4"></i>
                    </button>
                    <div class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenuButton">
                      <%= link_to query_room_device_path(device.room, device), method: :post, class: "dropdown-item text-info" do %>
                        <i class="bi-question-lg h4"></i> Query
                      <% end %>

                      <div class="dropdown-divider"></div>

                      <%= link_to edit_admin_room_device_path(device.room, device), class: "dropdown-item text-success" do %>
                        <i class="bi-pencil h4"></i> Edit
                      <% end %>
                    </div>
                  </div>
                </div>
              </h5>
              <p class="card-text">
                <h2 class="font-weight-light text-info">
                  <% sample = device.last_sample(data_type) %>
                  <% if sample %>
                    <%= sample.value %> <%= sample.unit %>
                  <% end %>
                </h2>

                <% samples = device.samples.where(data_type: data_type).order(created_at: :desc).limit(120) %>

                <% if samples.present? %>
                  <%= line_chart [{
                      name: data_type.name.capitalize,
                      data: samples.map { |e| [e.created_at, e.value] },
                      color: samples.first.html_color
                    }],
                    adapter: "highcharts",
                    height: "125px",
                    name: device.name,
                    library: {
                      time: {
                        timezone: Setting.time_zone,
                      },
                      chart: {
                        zoomType: 'x',
                        type: "area",
                        panning: true,
                        panKey: 'shift',
                        margin: [0, 0, 0, 0]
                      },
                      xAxis: {
                        visible: false
                      },
                      yAxis: {
                        visible: false
                      },
                      tooltip: {
                        enabled: true,
                        style: {
                          fontSize: '10px'
                        }
                      },
                      plotOptions: {
                        area: {
                          marker: {
                            enabled: false
                          }
                        }
                      }
                    }
                  %>
                <% end %>
              </p>
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/rooms/show.html.erb
<h1>
  <%= @room.name %> <span class="text-muted" style="font-size: 14px">
    [<%= @room.room_type.titleize %>] (<%= @room.length %> x <%= @room.width %> x <%= @room.height %>)
  </span>
  <div class="float-end" style="display: inline-flex">
    <%= link_to new_admin_room_device_path(@room), class: "btn btn-info d-flex align-items-center mr-1", style: "margin-right: 8px" do %>
      <i class="bi-plus my-1 h5"></i> Device
    <% end %>
    <%= link_to edit_admin_room_path(@room), class: "btn btn-success d-flex align-items-center" do %>
      <i class="bi-pencil my-1 h6" style="margin-right: 6px"></i> Edit
    <% end %>
  </div>
</h1>

<hr>

<% if @camera %>
  <img src="<%= @camera.custom_identifier %>" width="100%" class="img-fluid mb-4 rounded" />
<% end %>

<div class="row">
  <div class="col-sm-12 col-md-6 col-lg-3">
    <div class="card border-success mb-3">
      <div class="card-body text-success">
        <h5 class="card-title mb-0"><b><%= @room.total_watts %></b> Watts</h5>
      </div>
    </div>
  </div>
  <div class="col-sm-12 col-md-6 col-lg-3">
    <div class="card border-info mb-3">
      <div class="card-body text-info">
        <h5 class="card-title mb-0"><b><%= @room.kwh_day %></b> kWh / day</h5>
      </div>
    </div>
  </div>
  <div class="col-sm-12 col-md-6 col-lg-3">
    <div class="card border-primary mb-3">
      <div class="card-body text-primary">
        <h5 class="card-title mb-0"><b><%= @room.kwh_month %></b> kWh / month</h5>
      </div>
    </div>
  </div>
  <div class="col-sm-12 col-md-6 col-lg-3">
    <div class="card border-danger mb-3">
      <div class="card-body text-danger">
        <h5 class="card-title mb-0"><b><%= kwh_cost_estimation @room.kwh_month %></b> € / month</h5>
      </div>
    </div>
  </div>
</div>

<br>

<h4>
  Devices
  <div class="float-end">
    <%= link_to admin_room_devices_path(@room), class: "text-muted me-2", style: "font-size: 11px;" do %>
      <i class="bi-eye h4"></i> All devices
    <% end %>
    <%= link_to events_path(room_id: @room.id), class: "text-muted", style: "font-size: 11px;" do %>
      <i class="bi-eye h4"></i> All events
    <% end %>
  </div>
</h4>

<div class="row">
  <div class="col-sm-12 col-lg-6">
    <%= render partial: "rooms/room_devices", locals: {room: @room} %>
  </div>

  <div class="col-sm-12 col-md-12 col-lg-6">
    <%= render partial: "events/events", locals: {events: @room.all_events} %>
  </div>

<!--   <div class="col-sm-12 col-lg-3">
    <#%= render partial: "rooms/camshot", locals: {room: @room}  %>
  </div> -->
</div>

<br>

<h4>
  Subjects
</h4>

<%#= render partial: "admin/subjects/subjects_charts", locals: { subjects: @room.active_subjects } %>

<div class="row">
  <%= render partial: "admin/subjects/subjects", locals: { subjects: @room.active_subjects } %>
</div>

<% unless @room.scenarios.empty? %>
  <br>

  <% @room.scenarios.each do |scenario| %>
    <h4><%= scenario.name %></h4>

    <%= render partial: "admin/scenarios/scenario", locals: {scenario: scenario} %>

    <br>
  <% end %>
<% end %>