config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Root Settings for authenticated and unauthenticated users
  devise_scope :user do
    authenticated :user do
      root to: 'dashboard#index', as: :authenticated_root
    end

    unauthenticated do
      root to: 'devise/sessions#new'
    end
  end

  # Devise routes for users
  devise_for :users, skip: [:registrations]

  as :user do
    get 'users/edit/:id' => 'devise/registrations#edit', as: 'edit_user_registration'
    put 'users/:id' => 'devise/registrations#update'
  end

  # Standard routes
  resources :users, only: [:show]
  resources :batches
  resources :observations
  resources :devices, only: [:index]

  # Static page controllers
  get '/dashboard', to: 'dashboard#index'
  get '/journal', to: 'journal#index'
  get '/calendar', to: 'calendar#index'

  # Task-related routes
  resources :todos do
    member do
      post :done
      post :undone
    end
  end

  resources :notifications do
    collection do
      delete :clear_all
    end
  end

  resources :samples, only: [:index] do
    collection do
      get :general
      get :rooms
      get :harvest
    end
  end


  # Nested resources for grows
  resources :grows, except: %i[edit update new create] do
    resources :harvests, only: [:show]
    resources :weeks
    resources :observations
    resources :subjects do
      resources :observations
    end

    member do
      get :print_qr
    end
  end

  # Room-related resources
  resources :rooms, only: [:show] do
    resources :devices, only: [:show] do
      post :query, on: :member
      resources :events # Hinzufügen von Events unter Devices
    end

    resources :events
  end

  # Default events route (falls eigenständige events benötigt werden)
  resources :events
  resources :harvests, only: %i[index new]

  # Admin namespace
  namespace :admin do
    get '/dashboard/gpio', to: 'dashboard#gpio'

    resources :users, except: [:show] do
      member do
        get :update_password
      end
    end

    resources :grows, only: %i[edit update new create destroy] do
      resources :harvests, except: %i[index show] do
        resources :batches, except: %i[index show]
      end
      resources :subjects do
        post :move_to, on: :member
      end
    end

    resources :rooms do
      resources :devices, only: %i[index edit update new create destroy] do
        post :start, on: :member
        post :stop, on: :member
        resources :events
      end
    end

    resources :strains
    resources :data_types
    resources :batches
    resources :harvests
    resources :weeks

    resources :conditions do
      collection do
        get 'update', to: 'conditions#update'
      end
    end
    resources :batches, only: [:index, :show, :new, :create, :update, :destroy]

    resources :scenarios do
      member do
        get :load_condition_type_form
      end
      member do
        post 'run'
        get :export
        post :import
        get :import
      end
    end

    resources :devices do
      post :start, on: :member
      post :stop, on: :member
      post :query, on: :member
    end

    resources :circuits
    resources :components
    resources :device_scripts

    resources :scenarios do
      member do
        get :load_condition_type_form
      end
      member do
        post 'run'
      end
      collection do
        get :export
        post :import
      end
    end

    resources :condition_groups
    resources :conditions
    resources :operations

    resources :alerts do
      member do
        post :test
        post :trigger
      end
    end
    resources :categories
    resources :resources
    resources :observation_resources
    resources :issues, only: [:new, :destroy]

    resource :settings

    get '/', to: 'users#index'
  end

  # API namespace
  namespace :api do
    namespace :v1 do
      get '/context', to: 'context#index'

      resources :users, only: [:show] do
        resources :push_devices, only: [:create]
      end

      resources :devices, only: %i[index show update] do
        post :start, on: :member
        post :stop, on: :member
        resources :events # API-Unterstützung für verschachtelte Events unter Devices
      end

      resources :rooms
      resources :grows do
        resources :subjects
      end
      resources :subjects do
        resources :observations
      end
      resources :scenarios
      resources :conditions
      resources :operations
      resources :observations
      resources :events

      resources :data_types, only: %i[index show] do
        resources :samples, defaults: { format: :json }, only: %i[index show]
      end

      resources :samples, defaults: { format: :json }, only: %i[index show create]
    end
  end

  # API documentation
  apipie

  # Test route
  get 'test/index'
end

app/models/scenario.rb
# frozen_string_literal: true

# Scenario
class Scenario < ApplicationRecord
  attr_accessor :json_file

  belongs_to :subject, optional: true
  has_many :room_scenarios, dependent: :destroy
  has_many :rooms, through: :room_scenarios

  validates :name, presence: true

  has_many :condition_groups, dependent: :destroy
  has_many :conditions, through: :condition_groups
  has_many :operations, through: :condition_groups

  accepts_nested_attributes_for :condition_groups, allow_destroy: true, reject_if: :all_blank

  def as_json(*args)
    super.tap do |hash|
      # Ensure condition_groups is initialized as an array if nil
      hash['condition_groups'] ||= []

      hash['condition_groups'].each do |groups|
        groups.tap do |h|
          h['conditions_attributes'] = h.delete('conditions')
          h['operations_attributes'] = h.delete('operations')
        end
      end

      # Rename condition_groups to condition_groups_attributes
      hash['condition_groups_attributes'] = hash.delete('condition_groups')
    end
  end

  # rubocop:disable Metrics/MethodLength
  def run(room)
    return MB_LOGGER.info "Scenario #{name} skipped: disabled" unless enabled

    condition_groups.where(enabled: true).each do |group|
      MB_LOGGER.tagged("Scenario-#{id}") { MB_LOGGER.info "Checking condition group #{group.name}..." }

      all_conditions_met = group.conditions.all? do |condition|
        MB_LOGGER.tagged("Scenario-#{id}") { MB_LOGGER.info 'Evaluating condition...' }
        condition.check_condition(room)
      end

      if all_conditions_met
        MB_LOGGER.tagged("Scenario-#{id}") { MB_LOGGER.info 'All conditions met, executing operations...' }
        group.operations.each do |operation|
          sleep 2
          operation.execute_operation(room)
        end
      else
        MB_LOGGER.tagged("Scenario-#{id}") { MB_LOGGER.info 'Conditions not met' }
      end
    end
  end
  # rubocop:enable Metrics/MethodLength

  def self.run_scenarios
    MB_LOGGER.info '########################'
    MB_LOGGER.info '#  Run scenarios (v2)  #'

    Room.all.each do |room|
      room.scenarios.where(enabled: true).each do |scenario|
        MB_LOGGER.tagged("Scenario-#{scenario.id}") do
          MB_LOGGER.info "-> #{room.name} : #{scenario.name} [#{scenario.conditions.count} conditions]"
        end

        scenario.run(room)
      end
    end

    MB_LOGGER.info '########################'
  end

  def self.import(file_path, name)
    json_data = File.read(file_path)
    json = JSON.parse(json_data)

    scenario = Scenario.new(json)
    scenario.name = name

    scenario.save!
    scenario
  end
end

app/controllers/admin/scenarios_controller.rb
# frozen_string_literal: true

module Admin
  # Admin::ScenariosController
  class ScenariosController < Admin::AdminController
    include ApplicationHelper

    before_action :set_scenario, only: %i[show edit update destroy run export]
    before_action :set_room, only: %i[new show edit update destroy]

    # rubocop:disable Metrics/MethodLength
    def new
      @scenario = Scenario.new
    end

    def index
      @scenarios = Scenario.all
    end

    def edit
      @logics = Condition.logics.keys.map { |e| [Condition.logic_text(e.to_sym), e] }
      @condition_types = Condition.condition_types.keys.map { |e| [Condition.condition_type_text(e.to_sym), e] }
      @selected_condidion_type = 'date'
    end

    def create
      @scenario = Scenario.new(scenario_params)
      process_condition_durations(@scenario)

      respond_to do |format|
        if @scenario.save
          format.html do
            redirect_to admin_scenarios_path, notice: 'Scenario was successfully created.'
            format.turbo_stream
          end
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @observation.errors, status: :unprocessable_entity }
        end
      end
    end
    # rubocop:enable Metrics/MethodLength

    def update
      process_condition_durations(@scenario)

      respond_to do |format|
        if @scenario.update(scenario_params)
          format.html { redirect_to admin_scenarios_path, notice: 'Scenario was successfully updated.' }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @scenario.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @scenario.destroy
      respond_to do |format|
        format.html { redirect_to admin_scenarios_path, notice: 'Scenario was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    def load_condition_type_form
      @scenario = Scenario.find(params[:id])
      @condition_type = params[:type]

      respond_to do |format|
        format.html {
          render partial: "admin/scenarios/condition_forms/#{@condition_type}",
          locals: { f: view_context.form_for(@scenario) },
          layout: false
        }
      end
    end

    private

    def process_condition_durations(_scenario)
      params[:scenario][:condition_groups_attributes]&.each_value do |group|
        group[:conditions_attributes]&.each_value do |condition|
          if Condition.condition_types[condition[:condition_type]] == Condition.condition_types[:time_duration]
            duration_in_minutes = (condition[:time_duration_hours].to_i * 60) + condition[:time_duration_minutes].to_i
            condition[:duration] = duration_in_minutes
          end
        end
      end
    end

    # rubocop:disable Metrics/MethodLength
    def scenario_params
      params.require(:scenario).permit(
        :enabled,
        :name,
        :subject_id,
        :description,
        :json_file,
        condition_groups_attributes: [
          :id,
          :name,
          :scenario_id,
          :enabled,
          :_destroy,
          { conditions_attributes: %i[
              id
              data_type_id
              duration
              time_duration_hours
              time_duration_minutes
              predicate
              target_value
              start_time
              end_time
              condition_type
              logic
              condition_group_id
              _destroy
            ],
            operations_attributes: %i[
              id
              command
              delay
              retries
              duration
              device_type
              description
              condition_group_id
              _destroy
            ] }
        ]
      )
    end
    # rubocop:enable Metrics/MethodLength

    def set_scenario
      @scenario = Scenario.find(params[:id])
    end

    def set_room
      return unless params[:room_id].present?

      @room = Room.find(params[:room_id])
    end
  end
end

app/controllers/api/v1/scenarios_controller.rb
# frozen_string_literal: true

module Api
  module V1
    # ScenariosController
    class ScenariosController < ApiController
      before_action :set_scenario, only: %i[show edit update destroy]

      respond_to :json

      resource_description do
        short 'Scenarios '
        description 'Scenarios are used to automate operations based on a multiple conditions system.'
        meta 'Scenario' => %w[id name subject_id created_at updated_at]
        formats ['json']
        deprecated false
      end

      def_param_group :scenario do
        param :scenario, Hash do
          param :name, String, desc: 'The name of the scenario', required: true
          param :subject_id, :number, desc: 'The subject ID of the scenario', required: true
          param :description, String, desc: 'The description of the scenario', required: true
          param :created_at, DateTime, desc: 'The creation date', required: false
          param :created_at, DateTime, desc: 'The update date', required: false
        end
      end

      # GET /scenarios
      api :GET, '/v1/scenarios', 'Get a list of scenarios'
      param :limit, :number, desc: 'Limit number of items (default: 100, max: 1000)'
      param :offset, :number, desc: 'Offset of items'
      param :sort_direction, %w[asc desc], desc: 'The sort direction key'
      param :sort_column, %w[id device_type device_state name product_reference description last_start_date
                             created_at updated_at], desc: 'The sort column name'
      def index
        @items = Scenario.all

        @items = if params.key?(:sort_direction) && params.key?(:sort_column)
                   @items.order("#{params[:sort_column]} #{params[:sort_direction]}")
                 else
                   @items.order(created_at: :asc)
                 end

        @items = if params.key? :limit
                   @items.limit(params[:limit])
                 else
                   @items.limit(100)
                 end

        @items = @items.offset(params[:offset]) if params.key? :offset

        render json: @items, include: { conditions: { include: :operations }, subject: {} }
      end

      # GET /scenarios/1
      api :GET, '/v1/scenarios/:id', 'Get a scenario item'
      def show
        render json: @scenario, include: { conditions: { include: :operations }, subject: {} }
      end

      # POST /scenarios
      api :POST, '/v1/scenarios', 'Create a new scenario'
      param_group :scenario
      def create
        @scenario = Scenario.new(scenario_params)

        respond_to do |_format|
          if @scenario.save
            render :show, status: :created, location: @scenario
          else
            render json: @scenario.errors, status: :unprocessable_entity
          end
        end
      end

      # PATCH/PUT /scenarios/1
      api :PATCH, '/v1/scenarios/:id', 'Update a scenario'
      param_group :scenario
      def update
        respond_to do |_format|
          if @scenario.update(scenario_params)
            render :show, status: :ok, location: @scenario
          else
            render json: @scenario.errors, status: :unprocessable_entity
          end
        end
      end

      # DELETE /scenarios/1
      api :DELETE, '/v1/scenarios/:id', 'Delete a scenario'
      def destroy
        @scenario.destroy
        head :no_content
      end

      private

      # Use callbacks to share common setup or constraints between actions.
      def set_scenario
        @scenario = Scenario.find(params[:id])
      end

      # rubocop:disable Metrics/MethodLength
      def scenario_params
        params.require(:scenario).permit(
          :name,
          :subject_id,
          :description,
          conditions_attributes: %i[
            id
            name
            data_type_id
            predicate
            target_value
            start_time
            end_time
            scenario_id
            _destroy
          ]
        )
      end
      # rubocop:enable Metrics/MethodLength
    end
  end
end

app/helpers/scenarios_helper.rb
# frozen_string_literal: true

# ScenariosHelper
module ScenariosHelper
end

app/views/admin/scenarios/_condition_fields.html.erb
<div class="card p-4 mb-3 condition-fields">
  <div class="form-inline pb-2 d-flex" style="position: relative" data-controller="condition-fields" data-new-record="<%= f.object.new_record? %>" >
    <%= f.select :logic,
      options_for_select(
        Condition.logics.keys.map { |e| [Condition.logic_text(e.to_sym), e] },
        f.object.logic
      ),
      {},
      class: "form-select me-2 w-auto"
    %>

    <%= f.select :condition_type,
      options_for_select(
        Condition.condition_types.keys.map { |e|
          [Condition.condition_type_text(e.to_sym), e]
        },
        f.object.condition_type
      ),
      {},
      class: "form-select me-2 w-auto ml-2",
      data: {
        "condition-fields-target": "conditionType",
        action: "change->condition-fields#changeConditionType"
      }
    %>

    <%# Date Fields %>
    <div data-condition-fields-target="dateFields" class="condition__field--hidden d-flex">
      <span class="me-2 mt-2">Between</span>
      <%= f.text_field :start_time, value: ftime(f.object.start_time), class: "form-control me-2 select-time" %>
      <span class="me-2 mt-2">And</span>
      <%= f.text_field :end_time, value: ftime(f.object.end_time), class: "form-control me-2 select-time" %>
    </div>

    <%# Duration Fields %>
    <div data-condition-fields-target="durationFields" class="condition__field--hidden d-flex">
      <span class="me-2 mt-2">Every</span>
      <%= f.number_field :time_duration_hours, value: f.object.time_duration_hours, placeholder: "Hours", class: "form-control me-2" %>
      <span class="me-2 mt-2">hour(s)&nbspand</span>
      <%= f.number_field :time_duration_minutes, value: f.object.time_duration_minutes, placeholder: "Minutes", class: "form-control me-2", max: 59, step: 5 %>
      <span class="me-2 mt-2">minutes</span>

    </div>

    <%# Data Type Select %>
    <div data-condition-fields-target="dataTypeFields" class="condition__field--hidden d-flex">
      <%= f.select :data_type_id, options_from_collection_for_select(DataType.all, "id", "name", f.object.data_type_id), {}, class: "form-select me-2 w-auto" %>
    </div>

    <%# Device Select %>
    <div data-condition-fields-target="deviceFields" class="condition__field--hidden d-flex">
      <%= f.select :device_id, options_from_collection_for_select(Device.all, "id", "name", f.object.device_id), {}, class: "form-select me-2 w-auto" %>
    </div>

    <%# Shared Fields %>
    <div data-condition-fields-target="predicateField" class="condition__field--hidden d-flex">
      <%= f.select :predicate, options_for_select([[">=", 0], ["<=", 1]], f.object.predicate), {}, class: "form-select me-2 w-auto" %>
    </div>

    <div data-condition-fields-target="targetValueField" class="condition__field--hidden d-flex">
      <%= f.number_field :target_value, placeholder: "Target value", class: "form-control me-2" %>
    </div>

    <button type="button" data-action="condition-fields#remove" class="btn btn-danger">Remove</button>
    <%= f.hidden_field :_destroy %>
  </div>
</div>

app/views/admin/scenarios/_condition_group_fields.html.erb
<div class="nested-form-condition-group-wrapper" data-new-record="<%= f.object.new_record? %>">
  <div class="card p-4 mb-3">
    <div class="row">
      <div class="col-1">
        <div class="form-group d-flex">
          <%= f.check_box :enabled, data: {toggle: "toggle", size: "small"} %>
        </div>
      </div>
      <div class="col-4">
        <div class="form-group">
          <%= f.text_field :name, placeholder: "Condition name...", class: "form-control mx-2" %>
          <%= f.hidden_field :_destroy %>
        </div>
      </div>
    </div>
    <div data-controller="condition">
      <h5>Conditions</h5>
      <div class="mt-3">
        <template data-condition-target="template">
          <div class="condition-fields">
            <%= f.fields_for :conditions, Condition.new, child_index: 'NEWRECORD', f: f do |ff| %>
              <%= render "condition_fields", :f => ff %>
            <% end %>
          </div>
        </template>

        <div class="condition-fields">
          <%= f.fields_for :conditions do |ff| %>
            <%= render "condition_fields", f: ff %>
          <% end %>
        </div>
        <div data-condition-target="target"></div>
        <button type="button" data-action="condition#add" class="btn btn-success">Add Condition</button>
      </div>
    </div>
    <hr>
    <div data-controller="operation">
      <h5>Operations</h5>
      <div class="mt-3">
        <template data-operation-target="template">
          <div class="operation-fields">
            <%= f.fields_for :operations, Operation.new do |ff| %>
              <%= render "operation_fields", :f => ff %>
            <% end %>
          </div>
        </template>

        <%= f.fields_for :operations do |ff| %>
          <%= render "operation_fields", f: ff %>
        <% end %>

        <div data-operation-target="target"></div>
        <button type="button" data-action="operation#add" class="btn btn-success">Add Operation</button>
      </div>
    </div>
  </div>
</div>

app/views/admin/scenarios/_form.html.erb
<div id="scenario-container" data-controller="scenario nested-form">
  <%= form_with model: [:admin, scenario],
                data: {
                  controller: 'nested-form',
                  nested_form_wrapper_selector_value: '.nested-form-condition-group-wrapper'
                },
                class: "col-md-12 col-lg-12 mx-auto" do |f|%>
    <div class="card p-4 mb-3">
      <h2>
        <% if scenario.new_record? %>
          New scenario
        <% else %>
          Edit scenario
        <% end %>

        <div class="actions float-right">
          <%= link_to 'Cancel', :back, class: "btn btn-light border" %>
          <% unless scenario.new_record? %>
            <%= link_to 'Destroy', admin_scenario_path(scenario), data: { turbo: :true, "turbo-method": "delete" }, class: "btn btn-danger" %>
          <% end %>
          <%= f.submit "Save", class: "btn btn-primary" %>
        </div>
      </h2>
      <br>
      <% if scenario.errors.any? %>
        <div class="alert alert-danger" id="error_explanation">
          <h4><%= pluralize(scenario.errors.count, "error") %> prohibited this scenario from being saved:</h4>

          <ul>
          <% scenario.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <div class="row">
        <div class="col-sm-1">
          <%= f.label :enabled, "Enabled", class: "col-form-label" %>
        </div>
        <div class="col-sm-4">
          <%= f.label :name, "Name", class: "col-form-label" %>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-1">
          <%= f.check_box :enabled, data: {toggle: "toggle", size: "sm"}, class: "form-check-input" %>
        </div>
        <div class="col-sm-4">
          <%= f.text_field :name, class: "form-control" %>
        </div>
      </div>

      <div class="row mt-3">
        <div class="col-sm-1">
          <%= f.label :description, "Description" %>
        </div>
        <div class="col-sm-4">
          <%= f.text_area :description, class: "form-control",cols: 30, rows: 4  %>
        </div>
      </div>
      <hr>
      <h4>Condition groups</h4>
      <template data-nested-form-target="template">
        <div class="nested-fields">
          <%= f.fields_for :condition_groups, ConditionGroup.new, child_index: 'NEW_RECORD' do |fields| %>
            <%= render "admin/scenarios/condition_group_fields", f: fields %>
          <% end %>
        </div>
      </template>

      <%= f.fields_for :condition_groups do |fields| %>
        <%= render "admin/scenarios/condition_group_fields", f: fields %>
      <% end %>

      <div data-nested-form-target="target"></div>
      <div class="mt-3 d-inline">
        <button type="button" data-action="nested-form#add" class="btn btn-success">Add Condition Group</button>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/scenarios/_operation_fields.html.erb
<div class="card p-4 mb-3">
  <div class="form-inline pb-2 d-flex" style="position: relative">
		<%= f.select :device_type, options_for_select(Device.device_types.keys.map { |e| [e.titleize, e]  }, f.object.device_type), {}, class: "form-select me-2 w-auto" %>
		<%= f.select :command, options_for_select(["start", "stop"], f.object.command), {}, class: "form-select me-2 w-auto" %>
		<%= f.number_field :duration, value: f.object.duration, placeholder: "Duration (sec)", class: "form-control me-2 w-auto" %>
		<button type="button" data-action="operation#remove" class="btn btn-danger">Remove</button>
		<%= f.hidden_field :_destroy %>
	</div>
</div>

app/views/admin/scenarios/_scenario.html.erb
<% scenario.condition_groups.each do |condition_group| %>
<div class="row">
	<% condition_group.operations.each do |operation| %>
		<div class="col-sm-12 col-md-12 col-lg-6">
			<div class="card mb-4">
				<div class="card-header">
			    <b><%= condition_group.name %></b>
			  </div>
			  <ul class="list-group list-group-flush">

							<li class="list-group-item">
								The device of type <b><%= operation.device_type %></b> should <b><%= operation.command %> </b>
								<% if operation.duration %>
									for <b><%= operation.duration %> sec. </b>
								<% end %>

								<% if operation.condition_group and operation.condition_group.conditions.empty? %>
								 	at <b>any conditions</b>.
								<% else %>
									if
								<% end %>
								<br>

								<% if operation.condition_group %>
									<% operation.condition_group.conditions.each_with_index do |condition, i| %>
									<% end %>
								<% end %>
							</li>

  			</ul>
			</div>
		</div>
	<% end %>
</div>
<% end %>

app/views/admin/scenarios/edit.html.erb
<%= render 'form', scenario: @scenario %>

app/views/admin/scenarios/index.html.erb
<h1>
  Scenarios
  <div class="float-end">
    <%= link_to "New", new_admin_scenario_path, class: "btn btn-info" %>
  </div>
</h1>

<%= form_for :scenario, url: import_admin_scenarios_path, method: :post, class: "col-12", data: { turbo_frame: "_top" } do |form| %>
  <div class="mb-3">
    <%= form.label :name, class: 'form-label' %>
    <%= form.text_field :name, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= form.label "JSON File", class: 'form-label' %>
    <%= form.file_field :json_file, class: "form-control" %>
  </div>
  <%= form.submit "Import", class: "btn btn-primary" %>
<% end %>

<br>

<table class="table table-sm">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>In use by</th>
      <th class="text-center" width="80px">Enabled</th>
      <th width="110px"></th>
    </tr>
  </thead>

  <tbody>
    <% if @scenarios %>
      <% @scenarios.each do |scenario| %>
        <tr id="<%= dom_id(scenario) %>">
          <td style="vertical-align: middle;">
            <b class="text-primary"><%= link_to scenario.name, admin_scenario_path(scenario) %></b>
          </td>
          <td style="vertical-align: middle;"><%= scenario.description %></td>
          <td style="vertical-align: middle;">
            <% scenario.rooms.each do |room| %>
              <%= link_to room do %>
                <span class="badge bg-info"><%= room.name %></span>
              <% end %>
            <% end %>
          </td>
          <td class="text-center" style="vertical-align: middle;">
            <% if scenario.enabled %>
              <i class="bi-check2 h4 text-success"></i>
            <% end %>
          </td>
          <td>
            <%= link_to "Run", run_admin_scenario_path(scenario), class: "btn btn-sm btn-outline-primary", data: { turbo_frame: "_top" } %>
            <%= link_to "Edit", edit_admin_scenario_path(scenario), class: "btn btn-sm btn-outline-success", data: { turbo_frame: "_top" } %>
          </td>
        </tr>
      <% end %>
    <% else %>
      <tr>
        <td style="vertical-align: middle;">
          <b class="text-primary">No Scenarios available</b>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/scenarios/new.html.erb
<%= link_to sanitize("&larr; Back to Scenarios"), admin_scenarios_path %>
<%= render 'form', scenario: @scenario %>

app/views/admin/scenarios/show.html.erb
<h1>
	<%= @scenario.name %>
	<div class="float-end">
		<%= link_to 'Back', admin_scenarios_path, class: "btn btn-light border" %>
    <%= link_to "Edit", edit_admin_scenario_path(@scenario), class: "btn btn-success" %>
    <%= link_to "Export", export_admin_scenario_path(@scenario), method: :get, class: "btn btn-secondary" %>
    <%= link_to "Run", run_admin_scenario_path(@scenario), method: :get, class: "btn btn-primary" %>
  </div>
</h1>

<hr>

<p><%= @scenario.description %></p>

<hr>

<%= render partial: "admin/scenarios/scenario", locals: {scenario: @scenario} %>