config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Root Settings for authenticated and unauthenticated users
  devise_scope :user do
    authenticated :user do
      root to: 'dashboard#index', as: :authenticated_root
    end

    unauthenticated do
      root to: 'devise/sessions#new'
    end
  end

  # Devise routes for users
  devise_for :users, skip: [:registrations]

  as :user do
    get 'users/edit/:id' => 'devise/registrations#edit', as: 'edit_user_registration'
    put 'users/:id' => 'devise/registrations#update'
  end

  # Standard routes
  resources :users, only: [:show]
  resources :batches
  resources :observations
  resources :devices, only: [:index]

  # Static page controllers
  get '/dashboard', to: 'dashboard#index'
  get '/journal', to: 'journal#index'
  get '/calendar', to: 'calendar#index'

  # Task-related routes
  resources :todos do
    member do
      post :done
      post :undone
    end
  end

  resources :notifications do
    collection do
      delete :clear_all
    end
  end

  resources :samples, only: [:index] do
    collection do
      get :general
      get :rooms
      get :harvest
    end
  end


  # Nested resources for grows
  resources :grows, except: %i[edit update new create] do
    resources :harvests, only: [:show]
    resources :weeks
    resources :observations
    resources :subjects do
      resources :observations
    end

    member do
      get :print_qr
    end
  end

  # Room-related resources
  resources :rooms, only: [:show] do
    resources :devices, only: [:show] do
      post :query, on: :member
      resources :events # Hinzufügen von Events unter Devices
    end

    resources :events
  end

  # Default events route (falls eigenständige events benötigt werden)
  resources :events
  resources :harvests, only: %i[index new]

  # Admin namespace
  namespace :admin do
    get '/dashboard/gpio', to: 'dashboard#gpio'

    resources :users, except: [:show] do
      member do
        get :update_password
      end
    end

    resources :grows, only: %i[edit update new create destroy] do
      resources :harvests, except: %i[index show] do
        resources :batches, except: %i[index show]
      end
      resources :subjects do
        post :move_to, on: :member
      end
    end

    resources :rooms do
      resources :devices, only: %i[index edit update new create destroy] do
        post :start, on: :member
        post :stop, on: :member
        resources :events
      end
    end

    resources :strains
    resources :data_types
    resources :batches
    resources :harvests
    resources :weeks

    resources :conditions do
      collection do
        get 'update', to: 'conditions#update'
      end
    end
    resources :batches, only: [:index, :show, :new, :create, :update, :destroy]

    resources :scenarios do
      member do
        get :load_condition_type_form
      end
      member do
        post 'run'
        get :export
        post :import
        get :import
      end
    end

    resources :devices do
      post :start, on: :member
      post :stop, on: :member
      post :query, on: :member
    end

    resources :circuits
    resources :components
    resources :device_scripts

    resources :scenarios do
      member do
        get :load_condition_type_form
      end
      member do
        post 'run'
      end
      collection do
        get :export
        post :import
      end
    end

    resources :condition_groups
    resources :conditions
    resources :operations

    resources :alerts do
      member do
        post :test
        post :trigger
      end
    end
    resources :categories
    resources :resources
    resources :observation_resources
    resources :issues, only: [:new, :destroy]

    resource :settings

    get '/', to: 'users#index'
  end

  # API namespace
  namespace :api do
    namespace :v1 do
      get '/context', to: 'context#index'

      resources :users, only: [:show] do
        resources :push_devices, only: [:create]
      end

      resources :devices, only: %i[index show update] do
        post :start, on: :member
        post :stop, on: :member
        resources :events # API-Unterstützung für verschachtelte Events unter Devices
      end

      resources :rooms
      resources :grows do
        resources :subjects
      end
      resources :subjects do
        resources :observations
      end
      resources :scenarios
      resources :conditions
      resources :operations
      resources :observations
      resources :events

      resources :data_types, only: %i[index show] do
        resources :samples, defaults: { format: :json }, only: %i[index show]
      end

      resources :samples, defaults: { format: :json }, only: %i[index show create]
    end
  end

  # API documentation
  apipie

  # Test route
  get 'test/index'
end

app/models/alert.rb
# frozen_string_literal: true

# Alert Model
class Alert < ApplicationRecord
  include ActionView::Helpers::TextHelper

  enum alert_type: { data_type_alert: 0, resource_alert: 1 }

  enum operator: {
    equal: 0,
    not_equal: 1,
    lesser: 2,
    greater: 3,
    lesser_or_equal: 4,
    greater_or_equal: 5
    # :like               => 6,
    # :not_like           => 7,
    # :contain 						=> 8,
    # :not_contain 				=> 9,
    # :start_with 				=> 10,
    # :not_start_with 		=> 11,
    # :end_with 					=> 12,
    # :not_end_with 			=> 13
  }

  belongs_to :data_type, optional: true
  belongs_to :resource, optional: true

  has_many :alert_users
  has_many :users, through: :alert_users

  has_many :alert_push_users, class_name: 'AlertPushUser'
  has_many :push_users, through: :alert_push_users, source: :user

  has_many :notifications, as: :notifiable, dependent: :delete_all
  has_many :events, as: :eventable, dependent: :destroy

  validates :value, presence: true
  validates :message, presence: true
  validates :alert_type, presence: true

  def title
    'Alert'
  end

  def email_subject
    "ALERT: #{title}"
  end

  def notifiable_color
    'danger'
  end

  def notifiable_icon
    'exclamation-triangle'
  end

  def notifiable_url
    Setting.app_hostname + Rails.application.routes.url_helpers.notifications_path
  end

  def test_alert
    trigger
    # self.users.each do |u|
    #   Notification.create!(
    #     user: u,
    #     notify_email: true,
    #     notifiable: self).notify()
    # end
  end

  def self.trigger
    MB_LOGGER.info('# Start Trigger Alerts ############')
    Alert.all.each(&:trigger)
    MB_LOGGER.info('# End Trigger Alerts ##############')
  end

  # rubocop:disable Metrics/PerceivedComplexity, Metrics/MethodLength, Metrics/CyclomaticComplexity
  def trigger
    return unless enabled?

    context_object = nil
    triggered = false

    if data_type_alert?
      last_sample = Sample.where(data_type_id: data_type.id).limit(1).first
      context_object = last_sample.device

      case operator.to_sym
      when :equal
        triggered = last_sample.value.to_d == value.to_d
        "#{last_sample.value.to_d} equal #{value.to_d}"
      when :not_equal
        triggered = last_sample.value.to_d != value.to_d
        "#{last_sample.value.to_d} not_equal #{value.to_d}"
      when :lesser
        triggered = last_sample.value.to_d < value.to_d
        "#{last_sample.value.to_d} lesser #{value.to_d}"
      when :greater
        triggered = last_sample.value.to_d > value.to_d
        "#{last_sample.value.to_d} greater #{value.to_d}"
      when :lesser_or_equal
        triggered = last_sample.value.to_d <= value.to_d
        "#{last_sample.value.to_d} lesser_or_equal #{value.to_d}"
      when :greater_or_equal
        triggered = last_sample.value.to_d >= value.to_d
        "#{last_sample.value.to_d} greater_or_equal #{value.to_d}"
        # when :like
        #   triggered = false
        #   info = "false"
        # when :not_like
        #   triggered = false
        #   info = "false"
        # when :contain
        #   triggered = false
        #   info = "false"
        # when :not_contain
        #   triggered = false
        #   info = "false"
        # when :start_with
        #   triggered = false
        #   info = "false"
        # when :not_start_with
        #   triggered = false
        #   info = "false"
        # when :end_with
        #   triggered = false
        #   info = "false"
        # when :not_end_with
        #   triggered = false
        #   info = "false"
      end

    elsif resource_alert?
      last_data = ObservationResource.where(resource_id: resource.id).order('created_at').last
      context_object = last_data.observation
    end
    # rubocop:enable Metrics/PerceivedComplexity, Metrics/MethodLength, Metrics/CyclomaticComplexity

    return unless triggered

    MB_LOGGER.info("  -> Alert triggered: #{message} - #{users.count} users")

    Event.create!(event_type: :alert, message:, eventable: self)

    Time.zone.now

    # if !latest_send or latest_send <= (now - 1.hour)

    users.each do |u|
      MB_LOGGER.info("  -> Before notify : #{u.inspect}")

      n = Notification.create!(user: u, notify_email: true, notifiable: self, notified: context_object)

      MB_LOGGER.info("  -> Notification : #{n.inspect}")

      n.notify
    end

    # self.latest_send = now
    # self.save
    # end
  end
end

app/controllers/admin/alerts_controller.rb
# frozen_string_literal: true

module Admin
  # Admin::AlertsController
  class AlertsController < Admin::AdminController
    before_action :set_alert, only: %i[show edit update destroy test clear trigger]

    # GET /alerts
    # GET /alerts.json
    def index
      @alerts = Alert.all.order(:created_at)
    end

    def clear; end

    # GET /alerts/1
    # GET /alerts/1.json
    def show; end

    # GET /alerts/new
    def new
      @alert = Alert.new
    end

    # GET /alerts/1/edit
    def edit; end

    # POST /alerts
    # POST /alerts.json
    def create
      @alert = Alert.new(alert_params)

      respond_to do |format|
        if @alert.save
          format.html { redirect_to admin_alerts_url, notice: 'Alert was successfully created.' }
          format.json { render :show, status: :created, location: @alert }
        else
          format.html { render :new }
          format.json { render json: @alert.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /alerts/1
    # PATCH/PUT /alerts/1.json
    def update
      respond_to do |format|
        if @alert.update(alert_params)
          format.html { redirect_to admin_alerts_path, notice: 'Alert was successfully updated.' }
          format.json { render :show, status: :ok, location: @alert }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @alert.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /alerts/1
    # DELETE /alerts/1.json
    def destroy
      @alert.destroy
      respond_to do |format|
        format.html { redirect_to admin_alerts_path, notice: 'Alert was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    def test
      @alert.test_alert

      if request.referrer.present?
        redirect_to request.referrer, notice: 'Alert was successfully tested.'
      else
        redirect_to admin_alerts_url, notice: 'Alert was successfully tested.'
      end
    end

    def trigger
      @alert.trigger

      if request.referrer.present?
        redirect_to request.referrer, notice: 'Alert was successfully tested.'
      else
        redirect_to admin_alerts_url, notice: 'Alert was successfully tested.'
      end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_alert
      @alert = Alert.find(params[:id])
    end

    def alert_params
      params.require(:alert).permit(
        :alert_type,
        :data_type_id,
        :resource_id,
        :operator,
        :value,
        :message,
        :enabled,
        :push_enabled,
        user_ids: [],
        push_user_ids: []
      )
    end
  end
end

app/helpers/alerts_helper.rb
# frozen_string_literal: true

# AlertsHelper
module AlertsHelper
end

app/views/admin/alerts/_form.html.erb
<%= form_with(model: [:admin, alert], local: true, class: "col-md-12 col-lg-8 mx-auto",  data: { turbo: :false }, id: "admin-alerts-form") do |form| %>
  <h1>
    <%= alert.new_record? ? "New alert" : "Editing alert" %>
    <div class="float-end">
      <%= form.submit "Save", class: "btn btn-primary" %>
    </div>
  </h1>

  <% if alert.errors.any? %>
    <div class="alert alert-danger" id="error_explanation">
      <h4><%= pluralize(alert.errors.count, "error") %> prohibited this alert from being saved:</h4>

      <ul>
      <% alert.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <hr>

  <div class="mb-3">
    <%= form.check_box :enabled, data: {toggle: "toggle", size: "sm"} %> Enabled
  </div>

  <div class="mb-3">
    <%= form.check_box :push_enabled, data: {toggle: "toggle", size: "sm"} %> Web Push Enabled
  </div>

  <hr>

  <div class="mb-3">
    <%= form.label :alert_type, class: 'form-label' %>
    <%= form.select :alert_type, options_for_select(Alert.alert_types.keys.map { |e| [e.titleize, e] }, form.object.alert_type), {}, class: "form-control alert_types" %>
  </div>

  <div id="data_type_alert" class="mb-3 alert_type_from_group">
    <%= form.label :data_type_id, class: 'form-label' %>
    <%= form.select :data_type_id, options_from_collection_for_select(DataType.all, "id", "name", form.object.data_type_id), {}, class: "form-control" %>
  </div>

  <div id="resource_alert" class="mb-3 alert_type_from_group">
    <%= form.label :resource_id, class: 'form-label' %>
    <%= form.select :resource_id, options_from_collection_for_select(Resource.all, "id", "name", form.object.resource_id), {}, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :operator, class: 'form-label' %>
    <%= form.select :operator, options_for_select(Alert.operators.keys.map { |e| [e.titleize, e] }, form.object.operator), {}, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :value, class: 'form-label' %>
    <%= form.text_field :value, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :message, class: 'form-label' %>
    <%= form.text_area :message, class: "form-control" %>
  </div>

  <br>

  <h4>Notified users</h4>

  <div class="mb-3">
    <table class="table">
    <%= form.collection_check_boxes :user_ids, User.all, "id", "email", class: "form-control" do |ff| %>
      <tr>
        <td>
          <%= ff.check_box %>
        </td>
        <td>
          <%= ff.object.username %>
        </td>
        <td>
           <%= ff.object.email %>
        </td>
        <td>
           <%= ff.object.push_devices.count %> push device(s)
        </td>
      </tr>

    <% end %>
    </table>
  </div>
<% end %>

<%= javascript_tag do %>import './views/admin/alerts/form';<% end %>

app/views/admin/alerts/create.turbo_stream.erb
<%= turbo_stream.replace "alerts" do %>
  <%= render 'form', alert: @alert %>
<% end %>

app/views/admin/alerts/create.turbo_stream_1.erb
<%= turbo_stream.replace "alerts" do %>
  <%= render 'form', alert: @alert %>
<% end %>

app/views/admin/alerts/destroy.turbo_stream.erb
<%= turbo_stream.remove dom_id(@alert) %>

app/views/admin/alerts/destroy.turbo_stream_1.erb
<%= turbo_stream.remove dom_id(@alert) %>

app/views/admin/alerts/edit.html.erb
<%= render 'form', alert: @alert %>

app/views/admin/alerts/index.html.erb
<h1>
  Alerts
  <div class="float-end">
    <%= link_to new_admin_alert_path, class: "btn btn-info btn d-flex align-items-center" do %>
      <i class="bi-plus my-1 h5"></i>
      New
    <% end %>
  </div>
</h1>

<table class="table">
  <thead>
    <tr>
      <th>Type</th>
      <th class="text-center">Parameter</th>
      <th>Operator</th>
      <th class="text-center">Value</th>
      <th>Message</th>
      <th class="text-center" width="80px">Enabled</th>
      <th>Push</th>
      <th width="200px"></th>
    </tr>
  </thead>

  <tbody>
    <% @alerts.each do |alert| %>
      <tr>
        <td>
          <span class="badge bg-<%= alert.data_type_alert? ? 'primary' : 'success' %>">
            <%= alert.alert_type.titleize %>
          </span>
        </td>
        <td class="text-center">
          <span class="badge bg-dark">
            <% if alert.data_type_alert? %>
              <%= alert.data_type.name.titleize %>
            <% else %>
              <%= alert.resource.name %>
            <% end %>
          </span>
        </td>
        <td><%= alert.operator %></td>
        <td class="text-center"><%= alert.value %></td>
        <td class="font-monospace"><%= alert.message %></td>
        <td><%= alert.enabled ? "<i class='bi-check h4 text-success'></i>".html_safe : "<i class='bi-clock h4'></i>".html_safe %></td>
        <td><%= alert.push_enabled ? "<i class='bi-check h4 text-success'></i>".html_safe : "<i class='bi-clock h4'></i>".html_safe %></td>
        <td>
          <%= link_to 'Edit', edit_admin_alert_path(alert), class: "btn btn-sm btn-outline-success" %>
          <%= link_to 'Test', test_admin_alert_path(alert), method: :post, class: "btn btn-sm btn-outline-warning" %>
          <%= link_to 'Destroy',  [:admin, alert], data: { turbo: :true, "turbo-method": "delete" }, class: "btn btn-outline-danger" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/alerts/index.turbo_stream.erb
<%= turbo_stream.replace "alerts" do %>
  <%= render partial: "alerts/index" %>
<% end %>

app/views/admin/alerts/index.turbo_stream_1.erb
<%= turbo_stream.replace "alerts" do %>
  <%= render partial: "alerts/index" %>
<% end %>

app/views/admin/alerts/new.html.erb
<%= render 'form', alert: @alert %>

app/views/admin/alerts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Alert type:</strong>
  <%= @alert.alert_type %>
</p>

<p>
  <strong>Data type:</strong>
  <%= @alert.data_type_id %>
</p>

<p>
  <strong>Resource:</strong>
  <%= @alert.resource_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @alert.user_id %>
</p>

<p>
  <strong>Operator:</strong>
  <%= @alert.operator %>
</p>

<p>
  <strong>Value:</strong>
  <%= @alert.value %>
</p>

<p>
  <strong>Message:</strong>
  <%= @alert.message %>
</p>

<%= link_to 'Edit', edit_admin_alert_path(@alert) %> |
<%= link_to 'Back', admin_alerts_path %>

app/views/admin/alerts/show.turbo_stream.erb
<%= turbo_stream.replace "alerts" do %>
  <%= render partial: "alerts/show" %>
<% end %>

app/views/admin/alerts/show.turbo_stream_1.erb
<%= turbo_stream.replace "alerts" do %>
  <%= render partial: "alerts/show" %>
<% end %>

app/views/admin/alerts/update.turbo_stream.erb
<%= turbo_stream.replace "alerts" do %>
  <%= render 'form', alert: @alert %>
<% end %>